# Example config, values are overwritten by arguments provided at the command-line

# Required arguments
bids_dir: /path/to/bids_dir
output_dir: /path/to/output_dir
analysis_level: index/participant

# Optional arguments
opt:
  runner:
  working_dir:
  containers:
  threads: 1
  index_path:
  b0_thresh: 10

# Index analysis-level arguments
index.overwrite: true

# General Participant analysis-level arguments
participant:
  query:
  b0_thresh: 10
  # Tractography analysis-level arguments
  tractography:
    single_shell: false
    shells:
    lmax:
    steps:
    streamlines: 10_000
  # Connectivity analysis-level arguments
  connectivity:
    atlas:
